<?php

/**
 * PluginVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVideo');
    }
}